### ISSUE TITLE
Issue with robots.txt wildcards/end anchors

### ISSUE THREAD

**Issue by SpiderBro** [t1gor/Robots.txt-Parser-Class#10]
The following robots.txt will be interpreted by the class as denying everything:

User-Agent: *
Disallow: /*
Allow: /$

However, Google will interpret this (correctly) as allowing the homepage only.

I wonder if it's possible to update the class to correctly interpret these rules?

Thanks!

**Comment by JanPetterMG** [comment]
This is a hard one for sure!

````
$parser = new RobotsTxtParser('
User-Agent: *
Allow: /$
Disallow: /
');
var_dump($parser->isAllowed("/")); // bool(true)
var_dump($parser->isAllowed("/asd")); // bool(false)
var_dump($parser->isAllowed("/asd/")); // bool(true) [BUG]
````

From the ````checkRule()```` function:
````
		$directives = array(self::DIRECTIVE_DISALLOW, self::DIRECTIVE_ALLOW);
		foreach ($directives as $directive) {
			if (isset($this->rules[$userAgent][$directive])) {
				foreach ($this->rules[$userAgent][$directive] as $robotRule) {
					// change @ for \@
					$escaped = strtr($robotRule, array("@" => "\@"));

					// match result
					if (preg_match('@' . $escaped . '@', $value)) {
						$result = ($rule === $directive);
					}
				}
			}
		}
````
The ````checkRule()```` function, and regex in general is way out of my comfort zone, but I'll look into it. No guarantees!
