### ISSUE TITLE
checkRule(): preg_quote() and dot star wildcard

### ISSUE THREAD

**Issue by Esowteric** [t1gor/Robots.txt-Parser-Class#14]
Hi, I have a very simple test:
User-agent: *
Allow: /
And I'm testing with the URL /

The allow rule is changed to /dot star, but when it is passed through preg_quote(), the dot and star are both escaped with backslashes, and preg_match() in checkRule() returns false.

If you take the rule/pattern and change the backslashed dot star back to .* (using str_replace()) just before preg_match(), preg_match (correctly) returns true.

Sorry, the web page is misformatting the wildcards and backslashes.

With good wishes,
Eric T.

**Comment by t1gor** [comment]
@Esowteric, sorry for not getting back to you on this for so long. Now the issue should be fixed: I changed the `preg_quote` to `strtr`: https://github.com/t1gor/Robots.txt-Parser-Class/blob/master/source/robotstxtparser.php#L513

Would be cool if you could confirm fix.

**Comment by JanPetterMG** [comment]
@t1gor Confirmed, also this issue is now fixed.

User-Agent: *
Allow: / 

require_once("/vendor/autoload.php"); 
$parser = new RobotsTxtParser(file_get_contents("robots.txt")); 

var_dump($parser->isDisallowed("/")); 
bool(false) 
var_dump($parser->isAllowed("/")); 
bool(true)
