### ISSUE TITLE
Some more ideas

### ISSUE THREAD

**Issue by t1gor** [t1gor/Robots.txt-Parser-Class#16]
- Add a method for getting the rules, but not a public array. Should return iterator
- Use iterators for matching rules
- Disassemble directives to a separate classes - if anyone has any design ideas - please fee free to comment here or contact me directly - igor.timoshenkov@gmail.com
- Raise coverage up to 50% (min)
- [GA for repo](https://github.com/igrigorik/ga-beacon)

**Comment by SheemaGul** [comment]
I Want To Validate Robots.txt Syntax...Kindly Explain This Coding ???!

<?php
    require_once('robotstxtparser.php');
    $parser = new RobotsTxtParser(file_get_contents('http://example.com/robots.txt'));
    $parser->setHttpStatusCode(200); // optional
    var_dump($parser->isDisallowed('/someurl', 'useragent'));
    var_dump($parser->isAllowed('/someotherurl.html', 'useragent'));
    var_dump($parser->getDelay('Yandex')); // optional
    print_r($parser->rules);
?>

**Comment by JanPetterMG** [comment]
The last line should be like this:
print_r($parser->getRules());

We need a better example, possibly multiple, showing the different abilities.
Stay tuned, I'll fix it

**Comment by SheemaGul** [comment]
Thank You So Much...!
But I Have Another Problem Related To This...
I Want To Validate Robots.txt Syntax According To This Folder... Kindly Help Me To Parse The Syntax... The Right Syntax For Robots.txt Or Error Will Be Display In The 2nd Textarea(robots-checker.php)...
[(form.htm)
(robots.js)
(robots-checker.php)
(validate.js)]

[form.txt](https://github.com/t1gor/Robots.txt-Parser-Class/files/75465/form.txt)
[robots.txt](https://github.com/t1gor/Robots.txt-Parser-Class/files/75466/robots.txt)
[robots-checker.txt](https://github.com/t1gor/Robots.txt-Parser-Class/files/75468/robots-checker.txt)
[validate.txt](https://github.com/t1gor/Robots.txt-Parser-Class/files/75469/validate.txt)

Actually This Is The Part Of My Training. I Am New In This Field. I Spent 15 Days On This Assignment But It Is Very Difficult For Me To Validate This Textarea...
Atleast Give Me Some Hint To Validate It...! :)

**Comment by SheemaGul** [comment]
I Found 1 Error In Your Code((t1gor/Robots.txt-Parser-Class))
On Line 439:
$stripped = explode($delimiter, $userAgent, 2)[0];
The Correct Syntax May Be Including This One:
$stripped = explode( $delimiter, $userAgent,2); $stripped= $stripped[0];

**Comment by Muskaan2015** [comment]
A.O.A!!!!!!!!!!
I want to parse Robots.txt with url that is entered in text box than when i click on Submit button, the following url validate its robots.txt file and show me errors line by line on my page.
kindly help to solve this problem.
i also read and apply your code but its not working in my code my form file is:
[Form.txt](https://github.com/t1gor/Robots.txt-Parser-Class/files/75508/Form.txt)

**Comment by JanPetterMG** [comment]
@SheemaGul That's no error, it is a valid php 5.4 syntax.
Also the tests did pass, no errors found.
Take a look here: http://php.net/manual/en/migration54.new-features.php

**Comment by SheemaGul** [comment]
Alright...
I Think It's The Problem Of My Wampserver. It Doesn't Support php 5.4 syntax...!

**Comment by JanPetterMG** [comment]
Then you really should update your servers... Also PHP 7 is here.
PHP 5.3 has been **End of Life** since 14 Aug 2014, about 1 year, 4 months ago.
Feel free to open a pull request with the fix.

**Comment by JanPetterMG** [comment]
@t1gor Any schedule for the v1.x rewrite?
I would love to contribute more, but right now I have some issues seeing how it all fits together. Personally I think it is a lot more complicated than the v0.x code (at least now, when it doesn't do anything), but the fact is I'm just a hobby developer, so that's probably explains why...
I would really appreciate it if you could take a look at it, even if it just means implementing the most essential parts. Thanks!

**Comment by SheemaGul** [comment]
Yes... 2nd Field Will Include The Correct robots.txt Syntax...
Alright. M Trying To Fix This Code...Thanks For Your Guidance...!
