### ISSUE TITLE
Clean-param parse

### ISSUE THREAD

**Issue by bopoda** [t1gor/Robots.txt-Parser-Class#17]
Need parse Clean-param value.
for example site http://www.aquaphor.ru/robots.txt

>Clean-param – это параметр для файла robots.txt, создан специально поисковой системой яндекс, для того, чтобы указать какие страницы нужно игнорировать к индексации, вот ознакомьтесь как составить правильный robots.txt.

Also, can you make public method to get all rules? for example try http://xbb.uz/web/robots.txt (Xbb_RobotsTxt->getDirectives())

**Comment by JanPetterMG** [comment]
Is there any information about ````Clean-param```` available in English ?
I get the idea of what it does, but I think it's best to know every aspect of what it's intended to do before I write any code...
Unfortunately Google Translate isn't reliable...

Also, do you have an list of URLs to robots.txt files where it's used?
May this be on a single web-page, or is this something that is being used all over Russia (or other regions of the world)?

**Comment by JanPetterMG** [comment]
How to implement this?
CleanParam doesn't change anything in the way the parser works, not at all. The only thing we can do about it, is making a tool for 3rd partys. At least that's how I see it.

CleanParam is going to be supported, I'll make sure that happens. But the question is how?

- [ ] Provide a function parsing an array, removing any CleanParam duplicates, and then return it to the user?
- [ ] Remove any CleanParam from the URL that is been checked by isAllowed?? I'm not sure if that's even allowed according to Yandex. Merging duplicate parameters yes, but not removing them?

Any ideas?

**Comment by JanPetterMG** [comment]
Closing this "Issue".
- 2 new features implemented in v0.2.
- 1 won't-fix.
