### ISSUE TITLE
SemVer versioning

### ISSUE THREAD

**Issue by barryvdh** [t1gor/Robots.txt-Parser-Class#21]
Thanks for creating this tool. I understand its still in alpha status, but would you consider following SemVer and adding a branch alias?

For example, tag 0.1.0 with the current codebase, and add 0.1-dev as branch alias in your composer.json file. If you change the public API, upgrade to 0.2.x.

This way, we don't get in trouble with big changes :)

**Comment by t1gor** [comment]
Hi, @barryvdh.

Thanks for this note, definitely worth doing :+1:

**Comment by t1gor** [comment]
Ok, I created a release and added a branch alias. 

https://packagist.org/packages/t1gor/robots-txt-parser#dev-master

Is that what you've been asking for?

**Comment by barryvdh** [comment]
Ehh, not exactly. I would have probably used 0.1.0 instead of 0.0.1, bit more common.
But I guess people can require 0.0.x now. And instead of `0.0.1.x-dev`, you could use `0.0-dev` (or `0.1-dev` for 0.1). Now people have to use `0.0.1.x`, that's a bit unusual.
And you don't need to tag dev versions (with -dev), just the normale releases (`0.1.0`, `0.1.1` etc, or `0.2-alpha`, `0.2-beta` if you must.

So I would tag `0.1.0` and change the branch alias to `0.1-dev`.

**Comment by t1gor** [comment]
Aha, ok - thanks. This is a bit new for me :)
