### ISSUE TITLE
не обрабатывает правила

### ISSUE THREAD

**Issue by nejtr0n** [t1gor/Robots.txt-Parser-Class#22]
Пример
require_once 'src/autoload.php';
$robots_old = new \RobotsTxtParser(file_get_contents('robots.txt'));
var_dump($robots_old->isAllowed("/index"));
var_dump($robots_old->isDisallowed("/index"));

Фаил robots.txt
User-Agent: *
Disallow: /

Результат
bool(false) 
bool(false)

**Comment by JanPetterMG** [comment]
Hi, I always gets the same result, no matter wich path or robots.txt file I'm trying on. It has been like this since I first tested this script 2 months ago.
It's possible its just me, but all tests I have done, since the first time, shows the same result, isAllowed=false and isDisallowed=false.
PHP 5.6.7-1 (cli) (built: Mar 24 2015 12:30:15)

**Comment by JanPetterMG** [comment]
Is there any workaround, or earlier versions that I can test? I have tried investigate the master code, but my php skills isn't good enough to find the problem.
I have also tried the v1.0.0 code, it's a bit more complicated, and I don't understand how to use it. Do you have an example?
Does it work in any earlier php versions? I'm running php 5.6.7-1.

**Comment by t1gor** [comment]
Hi, @JanPetterMG . Seems like I have broken something within the package ... as I don't have much time lately to fix it, I suggest you choose some of the earlier revisions of the script, like this: https://github.com/t1gor/Robots.txt-Parser-Class/tree/11afc63786961e5b1213c48aa2646157d13c342d

Please try that and let me know if it works.

**Comment by t1gor** [comment]
Ok, the issue should be fixed now. I also created a test for that - https://github.com/t1gor/Robots.txt-Parser-Class/blob/master/test/cases/DisallowAll.php

Please feel free to add anything you consider relevant. It would also help if you could confirm is the fix is verified.

**Comment by JanPetterMG** [comment]
I have done some testing of older versions of this parser script, but haven't any of them to work at all, even the first version ever released, did not work. I guess they were not php 5.6 compatible.

The good news is that I now can confirm its working in some cases, but not all.

////////// Example 1: Not working //////////
User-Agent: *
Disallow: /admin/ 

require_once(dirname(__FILE__) . "/vendor/autoload.php"); 
$parser = new RobotsTxtParser(file_get_contents("robots.txt")); 

var_dump($parser->isDisallowed("/")); 
bool(false) 
var_dump($parser->isAllowed("/")); 
bool(false)

////////// Example 2: Not working //////////
User-Agent: *
Disallow: /admin/ 

require_once(dirname(__FILE__) . "/vendor/autoload.php"); 
$parser = new RobotsTxtParser(file_get_contents("robots.txt")); 

var_dump($parser->isDisallowed("/test/")); 
bool(false) 
var_dump($parser->isAllowed("/test/")); 
bool(false)

////////// Example 3: Working perfectly //////////
User-Agent: *
Disallow: / 

require_once(dirname(__FILE__) . "/vendor/autoload.php"); 
$parser = new RobotsTxtParser(file_get_contents("robots.txt")); 

var_dump($parser->isDisallowed("/index")); 
bool(true) 
var_dump($parser->isAllowed("/index")); 
bool(false)

**Comment by t1gor** [comment]
@JanPetterMG ok, thanks for the test input. I will submit some more code shortly

**Comment by JanPetterMG** [comment]
Does anyone know why this simple example does not work?
```$parser->isDisallowed("/path/")``` returns ```fatal error```. (```isAllowed``` equals ```isDisallowed```)
Test against ```/admin/``` is disallowed, but ```/path/``` fails...

```
User-agent: *
Disallow: /admin/
```

```
require_once(dirname(__FILE__) . '/../../../vendor/t1gor/robots-txt-parser/source/robotstxtparser.php'); 
$parser = new RobotsTxtParser(file_get_contents("robots.txt")); 

var_dump($parser->isDisallowed("/path/")); 

Fatal error: Uncaught exception 'DomainException' with message 'Unable to check rules' in robotstxtparser.php:488 Stack trace: #0 robotstxtparser.php(517): RobotsTxtParser->checkEqualRules('/path/', '*') #1 test.php(31): RobotsTxtParser->isDisallowed('/path/') #2 {main} thrown in robotstxtparser.php on line 488
```

**Comment by t1gor** [comment]
@JanPetterMG might be the regex, need to check ...

**Comment by JanPetterMG** [comment]
I think we could close this one?
Fix implemented and everything looks good.
Please re-open if anyone encounter more problems.

**Comment by t1gor** [comment]
@JanPetterMG :+1:
