### ISSUE TITLE
Empty robots.txt should allow everything

### ISSUE THREAD

**Issue by DrakeES** [t1gor/Robots.txt-Parser-Class#23]
Should not the following produce `bool(true)` at all times?
```php
$robots = new \RobotsTxtParser('');
var_dump($robots->isAllowed('/foo'));
```
It is currently producing `bool(false)` :(

**Comment by t1gor** [comment]
@DrakeES [this](https://github.com/t1gor/Robots.txt-Parser-Class/blob/master/source/robotstxtparser.php#L499) should have fixed the issue. Could you please confirm that?

**Comment by JanPetterMG** [comment]
@t1gor I can confirm this issue now is fixed.

$parser = new RobotsTxtParser(""); 
var_dump($parser->isDisallowed("/")); 
bool(false) 
var_dump($parser->isAllowed("/")); 
bool(true)

**Comment by t1gor** [comment]
@JanPetterMG thanks!

**Comment by JanPetterMG** [comment]
I think there is a unexpected problem, which complicates everything a little bit. I just discovered a robots.txt file that only contains sitemaps. It's as far as I know a rare case, so no big deal really, but it shuld be fixed some day... (low priority).

Example robots.txt file:
```
Sitemap: http://example.com/sitemap.xml 
```
```
Sitemap: http://example.com/sitemap.xml 

require_once("/vendor/autoload.php"); 
$parser = new RobotsTxtParser(file_get_contents("robots.txt")); 

var_dump($parser->isDisallowed("/")); 
bool(false) 
var_dump($parser->isAllowed("/")); 
bool(false) 
var_dump($parser->getSitemaps()); 
array(1) { [0]=> string(30) "http://example.com/sitemap.xml" } 
```
Source robots.txt file, where I discovered this: http://www.nettavisen.no/robots.txt
