### ISSUE TITLE
New directive: Cache-delay

### ISSUE THREAD

**Issue by JanPetterMG** [t1gor/Robots.txt-Parser-Class#37]
We need a new directive for ````Cache-delay````.

It's pretty much identical to Crawl-delay, but often has a higher delay (where both exists).

**Comment by t1gor** [comment]
Can you provide some docs on the one? I couldn't find any mentions ...

**Comment by JanPetterMG** [comment]
I couldn't find much docs on this one me either, but I'm pretty sure the cache-delay is handled the same way crawl-delay is.

My guess: The difference is what kind of robot scanning the page, is it caching a whole page (including all content, like a web browser), or is it just crawling one URL at a time. You could see it like crawling an extra 10-50 or maybe even more URLs at the same time, demanding more computing-power on the host server. In practice, this is more or less illegal to do according to crawl-delay.
I don't know if this theory is right, It's just what I think is most logical.

After googling a little bit, it's mainly found on Norwegian pages, so it may be something special rarely found on other pages.
- http://www.vg.no/robots.txt
- http://pent.no/robots.txt
- http://e24.no/robots.txt
- http://deltager.no/robots.txt
- http://www.funksjonell.no/robots.txt
- http://www.dinepenger.no/robots.txt
- http://www.ntb.no/robots.txt
Also found 1 in Denmark:
- http://finans.dk/robots.txt
All of these listed pages is using both crawl-delay and cache-delay.
