### ISSUE TITLE
Feature request: Handling HTTP result codes

### ISSUE THREAD

**Issue by JanPetterMG** [t1gor/Robots.txt-Parser-Class#41]
A blank HTTP response isn't always a "full allow", that actually depends on the HTTP status code. The Robots.txt-Parser-Class does simply return "full allow" if no valid robots.txt file is found.

**5xx (server error)**
Server errors are seen as temporary errors that result in a "full disallow" of crawling. The request is retried until a non-server-error HTTP result code is obtained. A 503 (Service Unavailable) error will result in fairly frequent retrying. To temporarily suspend crawling, it is recommended to serve a 503 HTTP result code. Handling of a permanent server error is undefined.

Source: https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt#handling-http-result-codes

Also, is this project more or less inactive for a shorter period of time, or whats the status?
I'm looking forward to fix a lot issues next year (that's not even on the Issues list), and also implement a lot of new features, but that will not happen if there is no one to merge pull requests or release the code as tags or version numbers. Then I want to fork this project, to fix it myself in a separate git. I don't want to steal the code, actually I love what's done so far, and I know it has been hard work, but right now, nothing happens when I push new pull requests...

**Comment by t1gor** [comment]
Hi, @JanPetterMG.

Sorry for not being there for you lately :( hate myself for that.

I actually had a plan to re-design the lib code (you can see an attempt here: https://github.com/t1gor/Robots.txt-Parser-Class/tree/v1.0.0). It's not yet done, thought, as a lot of things I have started so far.

How about having a discussion on what you would like to see, setting the milestones and doing minor releases? I would actually love to contribute more myself, and that's what I am about to do in the approaching year.

Please let me know your thoughts.

**Comment by JanPetterMG** [comment]
Thanks for adding me to this project, I really appreciate it :+1: :100: 

I haven't looked at the v.1.0.0 code for decades, fixing issues always has been top priority.
The new structure is definitely needed, as the current code are getting a bit large for a single file. If you could build up the main structure. Then I can do what I'm best at, fixing issues and build functionality. Building classes isn't my best field, sorry for that.
Keep up the good work.

Patches:
- Order of precedence for user-agents (#40). Some generic examples:
 - Googlebot-Image/1.0
 - Googlebot-Image
 - Googlebot

Minor:
- A robots.txt fetcher using curl (self assigned)
 - Taking care of HTTP status codes (this issue #41)
 - Not following redirects (to some 404 page, or even different host / sub-domains)
 - Ability to provide the full URL you want to access, and then parse the URL to find out witch robots.txt file to download based on host, scheme or even port. Because of this: https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt#examples-of-valid-robotstxt-urls
 - Issue #29: *iconv(): Detected an illegal character in input string* - will most likely be a huge problem, affecting a lot of users. Referencing to the issue for possible fix.

Milestone:
- Caching system (self assigned)

Maybe we should create a (really simple) Wiki page or something, to keep a up to date list of what's needed or what's coming. Easier than 30 comments in this thread, hehe.

How to implement a caching system you say? well, how about this: caching the files in a temporary directory on disk, checking the timestamps of the files to see if it needs an update.
Quick drafted code, witch also includes curl ( code not tested ):
````
<?php
$cacheLife = 86400; // 24 hours
if (!is_readable($path) || ((time() - filemtime($path)) > $cacheLife)) {
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_NOBODY, false);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
	$xml_content = curl_exec($ch);
	$http_statuscode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
	curl_close($ch);

	if (!empty($xml_content)) {
		// Only cache if there is content from request
		file_put_contents($path, $xml_content);
	}
} else {
	$xml_content = fread($path);
}
````
Note, this should not replace the ability to provide your own robots.txt content, but instead add the ability to download it automatically (with transparent caching).
Maybe create another class for this, witch using the existing (well working) parser class to parse the result?

**Comment by t1gor** [comment]
:) no problem, thanks for helping out!

Regarding the fetcher - in v1.0.0 I've introduced the `Content` classes, that are responsible for providing content to the parser. By default it should probably be [`StringContent`](https://github.com/t1gor/Robots.txt-Parser-Class/blob/v1.0.0/source/Content/StringContent.php), but I also have examples of [`EmptyContent`](https://github.com/t1gor/Robots.txt-Parser-Class/blob/v1.0.0/source/Content/EmptyContent.php) for unit tests and [`FileContent`](https://github.com/t1gor/Robots.txt-Parser-Class/blob/v1.0.0/source/Content/FileContent.php) for local files.

We can think about introducing some kind of `RemoteContent`which can then use cache, cURL and/or `GuzzleHttp`.

So generally - our thoughts on what to come do meet :+1: 

My main concern is that we should (probably?) both focus on new version, rather then supporting 2 versions in parallel. What do you think?

**Comment by JanPetterMG** [comment]
Agree!
How does this v1.0.0 branch work? Is it just splitting existing code into multiple classes, or is there bigger changes in the way it works? I'll see it's 5 months since last update, and a lot has happen since that...
