### ISSUE TITLE
Version 0.2.0 not on packagist

### ISSUE THREAD

**Issue by Kanti** [t1gor/Robots.txt-Parser-Class#58]
Why is version 0.2.0 not visible on packagist?
https://packagist.org/packages/t1gor/robots-txt-parser

**Comment by JanPetterMG** [comment]
Looks like @t1gor has to set up the "GitHub Service Hook" at Packagist.

In the meantime we have to live with Packagist's slow update detection rate :(

**Comment by t1gor** [comment]
Sorry, guys. V0.2 should be there: https://packagist.org/packages/t1gor/robots-txt-parser#0.2

I had email set up in Packagist hook rather then username.
