### ISSUE TITLE
Fail for rule containing $

### ISSUE THREAD

**Issue by LeMoussel** [t1gor/Robots.txt-Parser-Class#63]
Fail for rule containing '$'. 

To produce the bug:

```
        $robotsTxtContent = "
User-agent: *
Disallow: *deny_all/$";
        $robotsTxtParser = new RobotsTxtParser($robotsTxtContent);
        var_dump($robotsTxtParser->isAllowed("http://mysite.com/deny_all/") == false);  
// bool(false)
// BUG: Should return bool(true)
```

**Comment by JanPetterMG** [comment]
I would hold [/source/robotstxtparser.php line 844](https://github.com/t1gor/Robots.txt-Parser-Class/blob/master/source/robotstxtparser.php#L844) responsible for that one.

````
Disallow: *deny_all/$ // bug
Disallow: deny_all/$ // bug
Disallow: /deny_all/$ // works
````

**Comment by bopoda** [comment]
Just note:
if we check url "http://mysite.com/deny_all/"
according to https://www.google.com/webmasters/tools/robots-testing-tool should be:

- Disallow: *deny_all/$ http://joxi.ru/l2Znx3bIwkWp62 (isAllowed - false)
- Disallow: /deny_all/$ http://joxi.ru/Drl7BE6CvnOpNA  (isAllowed - false)
- Disallow: deny_all/$ http://joxi.ru/n2YRXYbsoV6LjA  (isAllowed - true).

I am glad to say that here https://github.com/bopoda/robots-txt-parser/pull/44 rules validated correctly.
