### ISSUE TITLE
setUserAgent is ignored

### ISSUE THREAD

**Issue by JanPetterMG** [t1gor/Robots.txt-Parser-Class#68]
```
User-agent: googlebot
Disallow: /
```

```
$parser->setUserAgent('googlebot');
$parser->isAllowed("/"); // bool true - expected bool false - bug
```

setUserAgent is always overrided by isAllowed/isDisallowed parameter 2, witch in this case is null (unset). This is probably the easiest and most logic way to check an path, but you'll always test against the wrong user-agent, in this case \* (wildcard) witch does not have a single rule (therefore always allowed)

DON'T EVER DO THIS !!! An fix will probably require backwards-incompatible changes. The easiest thing to do is check your code, and fix it yourself, or wait for next mayor version...
Correct usage is to replace those two lines with:

```
$parser->isAllowed("/", 'googlebot'); // this works as expected
```

**Comment by szepeviktor** [comment]
She is the 3rd *witch* of today:
![witch](http://3.bp.blogspot.com/_Z7H2HR0Ms28/TLOe-9k-6_I/AAAAAAAAAR0/F0zwKN2utlY/s1600/transportationSMALL.jpg)

Could you switch witch?

**Comment by adakou** [comment]
public function isDisallowed($url, $userAgent = null)
    {
        $this->setUserAgent($userAgent);　← Is not this a cause?
        $url = $this->encode_url($url);
        return $this->checkRules(self::DIRECTIVE_DISALLOW, $this->getPath($url), $this->userAgent_match);
    }

**Comment by JanPetterMG** [comment]
I don't know why I didn't think about it previously...

Do you mind submitting an PR?

**Comment by JanPetterMG** [comment]
Closing this issue, see #82 for continuation...
