### ISSUE TITLE
Drop support for PHP 5.4?

### ISSUE THREAD

**Issue by JanPetterMG** [t1gor/Robots.txt-Parser-Class#73]
Do we still need active support for PHP 5.4 and 5.5 ?
Is PHP 5.6 possible, or should we go for 5.5 to give people a little more time?

PHP 5.5 is End of life...
http://php.net/supported-versions.php

Just want to hear your opinions...

**Comment by t1gor** [comment]
I'd say it's too early. What do you think?

**Comment by JanPetterMG** [comment]
Personally I think it's too early for 5.5, but hey, it's "End of Life", and it doesn't even get security updates anymore. When people _finally_ decide to upgrade their servers, they also get the latest releases from this repo... That easy it is...

The reason behind this issue/question is that I've written some code where I'm unable to get 100% code testing coverage, unless using PHP 5.6. It's PHP 5.5 compatible, but due to limitations in older versions of PHPUnit, I need to skip some tests for it to pass. Unsupported assert-methods...
I'm pretty sure it's PHP 5.4 compatible too, but no matter what I try, it's always failing.

The only PHP 5.4 workaround (so far), is to delete the tests that requires PHPUnit 5.2+ (PHP 5.6), witch declines the test coverage a little bit...
Skipping tests works fine in PHP 5.5, but seems to be ignored in PHP 5.4 (PHPUnit bug?)

- HHVM  code coverage 100%
- PHP 7.1 code coverage 100%
- PHP 7.0 code coverage 100%
- PHP 5.6 code coverage 100%
- PHP 5.5 passes _(skipped tests)_
- PHP 5.4 compatible _(can't prove it)_
- PHP 5.3 incompatible _(fixable, just needs an workaround)_

I think we should drop PHP 5.4 support, it's been "End of Life" for almost a year already...

**Comment by JanPetterMG** [comment]
Anyone still requiring active PHP 5.4 support?
Can we bump to PHP 5.5 for next mayor version (v.0.3) ?
Now it's the time to scream...
